assets: /home/ubuntu/dsrl_pi0_v1/LIBERO/libero/libero/assets
bddl_files: /home/ubuntu/dsrl_pi0_v1/LIBERO/libero/libero/bddl_files
benchmark_root: /home/ubuntu/dsrl_pi0_v1/LIBERO/libero/libero
datasets: /home/ubuntu/dsrl_pi0_v1/LIBERO/libero/datasets
init_states: /home/ubuntu/dsrl_pi0_v1/LIBERO/libero/libero/init_files
